### ISSUE TITLE
Add dungeons

### ISSUE THREAD

**Issue by Owenm05** [Owenm05/Grimm-Tales#18]
Dungeons will be multiple fights in a row that starts with x weak enemies, when they are beaten it goes to x medium, and ends with a boss which is the hardest enemy of all. weakest enemies will have the most amount of total enemies medium will have less and so on. There will be stations to partially heal 80% of max hp after every phase. The player will not have a chance to escape after they start the dungeons

**Comment by Owenm05** [comment]
@Areso does everything look good this is only the start? [link](https://github.com/Owenm05/Grimm-Tales/commit/889b0066460eee348aae19516a75dec9e758cc46)

**Comment by Areso** [comment]
@Owenm05 to be honest, so far I don't understand why do you need a separate function dungeon_fight()
Except that, everything looks okay.

**Comment by Owenm05** [comment]
Mainly because I was unable to make it work when I tried to make it work in the other function if you if you can make this in the other function or give me an idea how to please do so thanks

**Comment by Owenm05** [comment]
More or less works though

**Comment by Areso** [comment]
Kinda fixed all that in https://github.com/Owenm05/Grimm-Tales/pull/20 PR.
